### ISSUE TITLE
Nice Work!

### ISSUE THREAD

**Issue by GeopJr** [Hey/Discord-JS-Cleverbot-Example#1]
About you second "Known Bug" , just replace `message.content.startsWith` with `message.content.includes`.
Also 

> Then do npm install discord.js then wait for it to install. After that do npm install cleverbot-node wait for it.

You could add a package.json and replace the above commands with `npm install` . 

(PS , I was just looking around and your project was looking nice 👍)

**Comment by Stijny** [comment]
Hey,


Thanks for helping me make this better. <3
When I'm home I will test the `message.content.includes` thing.
I'll also add the package.json not sure because some people just want to add the cleverbot part so I think I'll keep it like this but thanks for the suggestion.

**Comment by Stijny** [comment]
Thanks for helping.
Locking this.
